//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SringHelpMainFrom
{
    using System;
    using System.Collections.Generic;
    
    public partial class Exam_StudentPaperDetail
    {
        public System.Guid StudentPaperDetailId { get; set; }
        public Nullable<System.Guid> StudentPaperId { get; set; }
        public Nullable<System.Guid> PaperStructureId { get; set; }
        public Nullable<System.Guid> QuestionId { get; set; }
        public Nullable<int> QuestionType { get; set; }
        public string StudentAnswerText { get; set; }
        public Nullable<System.Guid> StudentAnswerOptionId { get; set; }
        public Nullable<double> Score { get; set; }
        public Nullable<System.Guid> GradeBy { get; set; }
        public Nullable<System.DateTime> GradeDate { get; set; }
        public Nullable<System.Guid> CheckBy { get; set; }
        public Nullable<System.DateTime> CheckDate { get; set; }
        public Nullable<int> Status { get; set; }
        public string ErrorType { get; set; }
        public string ErrorComment { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.Guid> LastUpdatedBy { get; set; }
        public Nullable<System.DateTime> LastUpdatedDate { get; set; }
        public Nullable<bool> DeleteStatus { get; set; }
        public Nullable<System.Guid> TenantId { get; set; }
        public string Result { get; set; }
        public Nullable<System.Guid> QuestionResolveActionId { get; set; }
        public Nullable<double> GradeScore { get; set; }
        public string QuestionJson { get; set; }
        public Nullable<int> Sort { get; set; }
    }
}
