//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SringHelpMainFrom
{
    using System;
    using System.Collections.Generic;
    
    public partial class Exam_Papers
    {
        public System.Guid PaperId { get; set; }
        public Nullable<System.Guid> ExamId { get; set; }
        public string PaperName { get; set; }
        public string PaperFileId { get; set; }
        public string PaperFilePath { get; set; }
        public string PaperFormJson { get; set; }
        public Nullable<System.Guid> CheckBy { get; set; }
        public Nullable<System.DateTime> CheckDate { get; set; }
        public Nullable<int> CurrentIndex { get; set; }
        public Nullable<int> Type { get; set; }
        public Nullable<System.Guid> SectionId { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.Guid> LastUpdatedBy { get; set; }
        public Nullable<System.DateTime> LastUpdatedDate { get; set; }
        public Nullable<bool> DeleteStatus { get; set; }
        public string OrganizeId { get; set; }
        public string DepartmentId { get; set; }
        public Nullable<System.Guid> TenantId { get; set; }
    }
}
