//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SringHelpMainFrom
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EduEntities : DbContext
    {
        public EduEntities()
            : base("name=EduEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            //throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Base_User> Base_User { get; set; }
        public virtual DbSet<Exam_Content> Exam_Content { get; set; }
        public virtual DbSet<Exam_Papers> Exam_Papers { get; set; }
        public virtual DbSet<Exam_StudentPaperDetail> Exam_StudentPaperDetail { get; set; }
        public virtual DbSet<Exam_StudentPapers> Exam_StudentPapers { get; set; }
        public virtual DbSet<Base_Organize> Base_Organize { get; set; }
    }
}
