//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SringHel.NetFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Base_User
    {
        public string UserId { get; set; }
        public string EnCode { get; set; }
        public string Account { get; set; }
        public string Password { get; set; }
        public string Secretkey { get; set; }
        public string RealName { get; set; }
        public string NickName { get; set; }
        public string Nation { get; set; }
        public string RenCaiType { get; set; }
        public string TrainType { get; set; }
        public string TrainLevel { get; set; }
        public string ZhengZhi { get; set; }
        public string HeadIcon { get; set; }
        public string QuickQuery { get; set; }
        public string SimpleSpelling { get; set; }
        public Nullable<int> Gender { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public string Mobile { get; set; }
        public string Telephone { get; set; }
        public string Email { get; set; }
        public string OICQ { get; set; }
        public string WeChat { get; set; }
        public string MSN { get; set; }
        public string ManagerId { get; set; }
        public string Manager { get; set; }
        public string OrganizeId { get; set; }
        public string DepartmentId { get; set; }
        public string DepartmentName { get; set; }
        public string RoleId { get; set; }
        public string DutyId { get; set; }
        public string DutyName { get; set; }
        public string PostId { get; set; }
        public string PostName { get; set; }
        public string WorkGroupId { get; set; }
        public Nullable<int> SecurityLevel { get; set; }
        public Nullable<int> UserOnLine { get; set; }
        public Nullable<int> OpenId { get; set; }
        public string Question { get; set; }
        public string AnswerQuestion { get; set; }
        public Nullable<int> CheckOnLine { get; set; }
        public Nullable<System.DateTime> AllowStartTime { get; set; }
        public Nullable<System.DateTime> AllowEndTime { get; set; }
        public Nullable<System.DateTime> LockStartDate { get; set; }
        public Nullable<System.DateTime> LockEndDate { get; set; }
        public Nullable<System.DateTime> FirstVisit { get; set; }
        public Nullable<System.DateTime> PreviousVisit { get; set; }
        public Nullable<System.DateTime> LastVisit { get; set; }
        public Nullable<int> LogOnCount { get; set; }
        public Nullable<int> SortCode { get; set; }
        public Nullable<int> DeleteMark { get; set; }
        public Nullable<int> EnabledMark { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string CreateUserId { get; set; }
        public string CreateUserName { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public string ModifyUserId { get; set; }
        public string ModifyUserName { get; set; }
        public Nullable<System.Guid> TenantId { get; set; }
        public string IDNumber { get; set; }
    }
}
