//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SringHel.NetFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Exam_Content
    {
        public System.Guid ExamId { get; set; }
        public string ExamName { get; set; }
        public string ExamPassword { get; set; }
        public string ExamSection { get; set; }
        public Nullable<System.Guid> PaperTemplateId { get; set; }
        public Nullable<System.Guid> PreviousExamId { get; set; }
        public Nullable<System.Guid> ClassId { get; set; }
        public Nullable<System.Guid> LessonId { get; set; }
        public Nullable<System.Guid> TeacherId { get; set; }
        public string ExamNotice { get; set; }
        public Nullable<int> NoticeTiming { get; set; }
        public Nullable<int> IsPublic { get; set; }
        public Nullable<int> Timing { get; set; }
        public Nullable<System.DateTime> StarTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public Nullable<double> TotalScore { get; set; }
        public Nullable<System.Guid> GradeBy { get; set; }
        public Nullable<System.Guid> CheckBy { get; set; }
        public Nullable<int> Status { get; set; }
        public string ExamType { get; set; }
        public string BuildMode { get; set; }
        public string IsShare { get; set; }
        public string Remark { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.Guid> LastUpdatedBy { get; set; }
        public Nullable<System.DateTime> LastUpdatedDate { get; set; }
        public Nullable<bool> DeleteStatus { get; set; }
        public string OrganizeId { get; set; }
        public string DepartmentId { get; set; }
        public Nullable<System.Guid> TenantId { get; set; }
        public Nullable<int> ExpandTime { get; set; }
        public Nullable<bool> EnableHistory { get; set; }
        public Nullable<bool> EnableOptionRandom { get; set; }
        public Nullable<bool> EnableLeaveMoni { get; set; }
        public string ImageIds { get; set; }
        public Nullable<int> EnableCacheModel { get; set; }
    }
}
