//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SringHel.NetFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Exam_StudentPapers
    {
        public System.Guid StudentPaperId { get; set; }
        public Nullable<System.Guid> ExamId { get; set; }
        public Nullable<System.Guid> PaperId { get; set; }
        public string StudentPaperFormJson { get; set; }
        public Nullable<System.Guid> StudentId { get; set; }
        public Nullable<System.Guid> UserId { get; set; }
        public Nullable<System.DateTime> StarExamTime { get; set; }
        public Nullable<System.DateTime> EndExamTime { get; set; }
        public string StudentPaperFileId { get; set; }
        public string StudentPaperFilePath { get; set; }
        public Nullable<System.Guid> GradeBy { get; set; }
        public Nullable<System.DateTime> GradeDate { get; set; }
        public Nullable<System.Guid> CheckBy { get; set; }
        public Nullable<System.DateTime> CheckDate { get; set; }
        public Nullable<int> Status { get; set; }
        public string ErrorFeedBack { get; set; }
        public Nullable<double> Part1Score { get; set; }
        public Nullable<double> Part2Score { get; set; }
        public Nullable<double> Part3Score { get; set; }
        public Nullable<double> TotalScore { get; set; }
        public string ClientIP { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.Guid> LastUpdatedBy { get; set; }
        public Nullable<System.DateTime> LastUpdatedDate { get; set; }
        public Nullable<bool> DeleteStatus { get; set; }
        public string OrganizeId { get; set; }
        public string DepartmentId { get; set; }
        public Nullable<System.Guid> TenantId { get; set; }
        public Nullable<int> Batch { get; set; }
        public Nullable<int> ExamNumber { get; set; }
        public Nullable<int> AdjustmentTime { get; set; }
        public string IP { get; set; }
    }
}
